### ISSUE TITLE
Replace images

### ISSUE THREAD

**Issue by rettaboo78** [SmallWiseOneDesign/smallwiseone.github.io#7]
![Screenshot with Pics](https://github.com/user-attachments/assets/d15c78a4-70ce-436f-9afc-c2ee7cf47f01)

**Comment by rettaboo78** [comment]
in the Small Wise One folder you created and shared Small Wise One > Website > Images

**Comment by marknoble** [comment]
https://1drv.ms/f/s!AjijkVzsfoBNgfiYROPYwmcS6N9JNHg?e=BDqqtN
